# See for reference: https://aka.ms/yaml

# Trigger builds for all commits to master, and all PRs
trigger: [master]

jobs:
- job: check_formatting
  displayName: Check formatting
  pool:
      vmImage: ubuntu-latest
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      $HOME/.cargo/bin/rustup component add rustfmt
    displayName: Install Rust stable
  - script: $HOME/.cargo/bin/cargo fmt -- --check
    displayName: Run rustfmt
- job: check_tests
  displayName: Check tests
  pool:
      vmImage: ubuntu-latest
  steps:
  - script:
      curl https://sh.rustup.rs -sSf | sh -s -- -y
    displayName: Install Rust stable
  - script: $HOME/.cargo/bin/cargo test
    displayName: Run tests

- template: ./azure-pipelines-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-latest

- template: ./azure-pipelines-template.yml
  parameters:
    name: macOS
    vmImage: macOS-latest
