jobs:
- job: ${{ parameters.name }}
  pool:
      vmImage: ${{ parameters.vmImage }}
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install Rust
  - ${{ if eq(parameters.name, 'Linux') }}:
    - script: make build-linux-x64
      displayName: Build host (Linux)
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: Host for Linux
        targetPath: release/
  - ${{ if eq(parameters.name, 'macOS') }}:
    - script: make build-darwin-x64
      displayName: Build host (macOS)
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: Host for macOS
        targetPath: release/
