name: Check
on: [push, pull_request]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/registry
                  ~/.cargo/git
                  target
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - name: Check
              run: cargo check
            - name: Test
              run: cargo test
            - name: Lint
              # See: https://github.com/rust-lang/rust-clippy/issues/1209
              run: RUSTFLAGS="-D warnings" cargo clippy --all-targets
            - name: Check formatting
              run: cargo fmt -- --check
