name: Publish

on:
    push:
        tags: ["v[0-9].[0-9].[0-9]"]

jobs:
    publish:
        name: Publish for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: bukubrow
                      asset_name: bukubrow-linux-amd64
                    - os: macos-latest
                      artifact_name: bukubrow
                      asset_name: bukubrow-macos-amd64
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/registry
                  ~/.cargo/git
                  target
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - name: Build
              run: cargo build --release
            - name: Publish
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: target/release/${{ matrix.artifact_name }}
                asset_name: ${{ matrix.asset_name }}
                tag: ${{ github.ref }}
